- name: install core apps
  pacman:
   name:
    - curl
    - wget
    - git
    - 7zip
    - discord
    - eww
    - firefox
    - leftwm-git
    - lightdm
    - mumble
    - nemo
    - numlockx
    - nvidia-open
    - pulseaudio
    - steam
    - vlc
    - vlc-plugins-all
    - vscodium
   state: present
